# Generated by Django 5.2.11 on 2026-06-24 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('nomC', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField()),
                ('metier', models.CharField(choices=[('jardinier', 'Jardinier'), ('bawab', 'Bawab/Gardien'), ('cuisinier', 'Cuisinier/Cuisinière'), ('femme_menage', 'Femme de ménage'), ('chauffeur', 'Chauffeur'), ('nounou', "Nounou/Garde d'enfants")], default='femme_menage', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('element', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyAPPTodoLis.client')),
            ],
        ),
    ]
