# Generated by Django 5.2.11 on 2026-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPPTodoLis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nomC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pwd',
            field=models.CharField(max_length=100),
        ),
    ]
